function [scenario, egoVehicle] = Simulate()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 25.1 (R2025a) and Automated Driving Toolbox 25.1 (R2025a).
% Generated on: 14-Nov-2025 21:05:20

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [41.4 -10.4 0;
    6.3 -9.9 0];
road(scenario, roadCenters, 'Name', 'Road');

roadCenters = [34.8 14.4 0;
    34.7 -20.5 0];
road(scenario, roadCenters, 'Name', 'Road1');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Length', 4, ...
    'Width', 1.6, ...
    'Position', [8 -9.9 0], ...
    'RearOverhang', 1, ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [8 -9.9 0;
    14 -10.6 0;
    17.3 -10.6 0;
    21.9 -10.8 0;
    25.9 -9.7 0;
    31.6 -11.1 0;
    34.8 -9.1 0;
    35.6 1.2 0;
    34.3 10.8 0];
speed = [30;30;30;30;30;30;30;30;30];
trajectory(egoVehicle, waypoints, speed);

